### ISSUE TITLE
Can preallocate these mask arrays outside loop to avoid unnecessarily allocations

### ISSUE THREAD

**Issue by eford** [alexander-wise/RvLineList#21]
https://github.com/alexander-wise/RvLineList/blob/6f57cd6572fb8678bb252fe64019d1e76394317a/src/empirical_line_lists.jl#L45

**Comment by alexander-wise** [comment]
question: do I need to change the syntax inside the loop to make sure it doesn't re-allocate the memory? like

flux_nan_idx_ij[:] =
