### ISSUE TITLE
Use logical not bitwise operations 

### ISSUE THREAD

**Issue by eford** [alexander-wise/RvLineList#27]
https://github.com/alexander-wise/RvLineList/blob/6f57cd6572fb8678bb252fe64019d1e76394317a/src/empirical_line_lists.jl#L220

**Comment by eford** [comment]
Even if it's working, it still should be fixed.

**Comment by alexander-wise** [comment]
When I replace .| with .||, I get an error:

LoadError: syntax: "|" is not a unary operator

so it seems I have to use .| here
