### ISSUE TITLE
Take/return scalar

### ISSUE THREAD

**Issue by eford** [alexander-wise/RvLineList#35]
https://github.com/alexander-wise/RvLineList/blob/6f57cd6572fb8678bb252fe64019d1e76394317a/src/empirical_line_lists.jl#L292-L293
The caller can broadcast over multiple dates if they want to.

**Comment by alexander-wise** [comment]
note: commit c2e24acebcbb94396c2965b8ef6500c9813c1062 to reduce memory allocations originally mistakenly referenced this issue, but was renamed
